---
sidebar: sidebar 
permalink: create-workspaces.html 
keywords: manage, workspace, snapshot, project 
summary: Um espaço de trabalho no NetApp Workload Factory for Builders é uma representação Perforce de um projeto baseada em um instantâneo do projeto.  Você pode criar espaços de trabalho como parte de um projeto do Builders. 
---
= Crie um espaço de trabalho Builders
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Um espaço de trabalho no NetApp Workload Factory for Builders é uma representação Perforce de um projeto em um momento específico.  Os espaços de trabalho são criados usando um instantâneo do projeto como base.  Você pode criar novos espaços de trabalho dentro de um projeto do Builders.  Você pode criar espaços de trabalho a partir da interface do usuário do Perforce.

.Antes de começar
Certifique-se de que integrou o Builders com o Perforce Helix Visual Client. Consulte link:integrate-perforce.html["Integre construtores com Perforce"^] para obter mais informações.

.Passos
. Inicie sessão no Perforce.
. No menu Perforce, selecione *View* > *WF*.
+
A tela de login do Workload Factory aparece na interface do usuário do Perforce.

. Faça login no Workload Factory usando um doslink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^] .
. No bloco Cargas de trabalho do Builders, selecione *Criar projeto*.
. Selecione *criar espaço de trabalho*.
. Na página criar um projeto de área de trabalho, forneça o seguinte:
+
.. Selecione um instantâneo a ser usado como base para o espaço de trabalho.
.. Introduza um nome para a área de trabalho.
.. Opcionalmente, insira um identificador de usuário para reivindicar o espaço de trabalho. Esse identificador deve corresponder ao ID de usuário do Perforce do desenvolvedor que usará essa área de trabalho.


. Selecione *criar*.


.Resultado
A área de trabalho é criada e aparece na lista de espaços de trabalho na página espaços de trabalho.
