---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: O NetApp Workload Factory for Builders é uma ferramenta de criação rápida de ambientes de construção para desenvolvedores de software. 
---
= Saiba mais sobre o NetApp Workload Factory para construtores
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O NetApp Workload Factory for Builders é uma ferramenta de criação rápida de ambientes de construção para desenvolvedores de software.  Ele permite a configuração rápida de ambientes de desenvolvimento pessoal, economizando tempo e permitindo o autoatendimento para desenvolvedores, ao mesmo tempo em que capacita as equipes de DevOps a manter o controle da infraestrutura.  Usando o Builders, os desenvolvedores de software podem criar rapidamente espaços de trabalho sem precisar de armazenamento de dados especializado ou compreensão da infraestrutura de desenvolvimento.



== O que é o NetApp Workload Factory para construtores?

O NetApp Workload Factory for Builders foi projetado para simplificar a maneira como os desenvolvedores gerenciam e interagem com diferentes versões de seus softwares.  O Builders integra-se perfeitamente ao Perforce Helix Core para fornecer clones instantâneos de versões de software, criando espaços de trabalho prontos para uso para processos de desenvolvimento, controle de qualidade e CI/CD.

Com Builders, você pode facilmente criar um projeto e atribuir um volume que representa seu ambiente de software e seus artefatos. À medida que você atualiza seu software, você pode tirar snapshots do volume, capturando o estado do seu software naquele momento. Isso significa que você pode acessar qualquer versão do seu software instantaneamente sem a necessidade de ressincronizar com o sistema de controle de versão, economizando tempo e recursos valiosos.

Ao aproveitar os recursos de snapshot e clone do ONTAP, o Builders aprimora seu fluxo de trabalho de desenvolvimento, permitindo acesso rápido a várias versões do seu software, acelerando os ciclos de desenvolvimento e ajudando a reduzir o tempo de comercialização.

Para obter mais informações sobre o Workload Factory, consulte olink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Visão geral da Workload Factory"^] .



== Recursos do NetApp Workload Factory para construtores

O NetApp Workload Factory for Builders oferece os seguintes recursos:

* Crie, edite e remova projetos
* Criar instantâneos de versões de software definidas
* Criar e excluir espaços de trabalho (com base em clones)
* Crie políticas de acesso para controlar o acesso a um projeto
* Analise o uso da capacidade de cada projeto
* Controle os limites de tamanho do clone e a retenção de clones para cada projeto
* Integrar com sistemas de controle de versão, como o Perforce




== Projetos e espaços de trabalho em Builders

Quando você usa Builders, você cria um projeto e atribui um volume que representa seu ambiente de software e seus artefatos. Cada vez que você criar uma nova versão do software, você precisa sincronizar novamente os dados de volume e criar um instantâneo de projeto para marcar o estado do volume como uma versão conhecida. O volume de origem do projeto pode obter atualizações contínuas e ter vários snapshots para marcar várias versões. Você pode usar cada snapshot imediatamente como um clone instantâneo, um repositório editável dedicado ou compartilhado disponível para desenvolvedores, QA ou processos de compilação. Um clone no contexto de uma versão de software específica é um espaço de trabalho.



== Modos operacionais na Workload Factory

Três modos operacionais diferentes — _básico_, _somente leitura_ e _leitura/gravação_ — oferecem opções flexíveis para implantação dentro e fora do Workload Factory.  Obtenha valor imediato em confiança zero no modo _básico_ com trechos de código para uso fora do Workload Factory.  Obtenha valor incremental com confiança incremental nos modos _somente leitura_ e _leitura/gravação_.

Saiba mais sobre link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["modos operacionais na Workload Factory"^] .



== Automação com Workload Factory Codebox

A fábrica de carga de trabalho introduz a automação incorporada com o _Codebox_. O Codebox oferece os seguintes benefícios de automação:

* *Geração de snippets de código*: Snippets de infraestrutura como código (IAC) são gerados durante a criação de recursos, permitindo uma integração perfeita com fluxos de trabalho de orquestração existentes.
* *Copiloto de infraestrutura como código*: o Codebox é um copiloto de infraestrutura como código (IaC) que ajuda desenvolvedores e DevOps a gerar código para executar qualquer operação suportada pelo Workload Factory.
* *Visualizador de código e catálogo de automação*: O Codebox fornece um visualizador de código para análise rápida da automação e um catálogo de automação para rápida reutilização futura.




== Custo

Não há custo para usar o recurso Builders do Workload Factory.



== Licenciamento

Não são necessárias licenças especiais da NetApp para usar os recursos do Builders do Workload Factory.



== Regiões

Os construtores têm suporte em todas as regiões comerciais onde o FSX for ONTAP é compatível. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Exibir regiões da Amazon compatíveis."^]

As seguintes regiões da AWS não são suportadas:

* Regiões da China
* Regiões GovCloud (EUA)
* Nuvem secreta
* Top nuvem secreta




== Obter ajuda

O Amazon FSX for NetApp ONTAP é uma solução exclusiva da AWS. Para dúvidas ou problemas de suporte técnico associados ao ONTAP sistema de arquivos, infraestrutura ou qualquer solução usando este serviço, use a Central de suporte no Console de Gerenciamento da AWS para abrir um caso de suporte com a AWS. Selecione o serviço "FSX for ONTAP" e a categoria apropriada. Forneça as informações restantes necessárias para criar seu caso de suporte da AWS.

Para perguntas gerais sobre o Workload Factory ou aplicativos e serviços do Workload Factory, consultelink:get-help-builders.html["Obtenha ajuda para construtores do Workload Factory"] .
