---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: O NetApp Workload Factory for Builders é uma ferramenta de criação rápida de ambientes de construção para desenvolvedores de software. 
---
= Saiba mais sobre o NetApp Workload Factory para construtores
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O NetApp Workload Factory for Builders é uma ferramenta de criação rápida de ambientes de construção para desenvolvedores de software.  Ele permite a configuração rápida de ambientes de desenvolvimento pessoal, economizando tempo e permitindo o autoatendimento para desenvolvedores, ao mesmo tempo em que capacita as equipes de DevOps a manter o controle da infraestrutura.  Usando o Builders, os desenvolvedores de software podem criar rapidamente espaços de trabalho sem precisar de armazenamento de dados especializado ou compreensão da infraestrutura de desenvolvimento.



== O que é o NetApp Workload Factory para construtores?

O NetApp Workload Factory for Builders foi projetado para simplificar a maneira como os desenvolvedores gerenciam e interagem com diferentes versões de seus softwares. O Builders funciona com o Perforce Helix Core para clonar instantaneamente versões de software e criar espaços de trabalho para desenvolvimento, controle de qualidade e CI/CD.

Com o Builders, você pode facilmente criar um projeto e atribuir um volume que represente seu ambiente de software e seus artefatos. Ao atualizar seu software, você pode tirar instantâneos do volume, capturando o estado do seu software naquele momento. Você pode acessar qualquer versão de software instantaneamente, sem precisar resincronizar, economizando tempo e recursos.

Utilizando os recursos de snapshot e clonagem do NetApp ONTAP, o Builders permite acessar diferentes versões do seu software mais rapidamente, para que você possa desenvolver e lançar atualizações com maior agilidade.

Para obter mais informações sobre o Workload Factory, consulte olink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Visão geral da Workload Factory"^] .



== Recursos do NetApp Workload Factory para construtores

O NetApp Workload Factory for Builders oferece os seguintes recursos:

* Crie, edite e remova projetos
* Criar instantâneos de versões de software definidas
* Criar e excluir espaços de trabalho (com base em clones)
* Crie políticas de acesso para controlar o acesso a um projeto
* Analise o uso da capacidade de cada projeto
* Controle os limites de tamanho do clone e a retenção de clones para cada projeto
* Integrar com sistemas de controle de versão, como o Perforce




== Projetos e espaços de trabalho em Builders

Quando você usa Builders, você cria um projeto e atribui um volume que representa seu ambiente de software e seus artefatos. Cada vez que você criar uma nova versão do software, você precisa sincronizar novamente os dados de volume e criar um instantâneo de projeto para marcar o estado do volume como uma versão conhecida. O volume de origem do projeto pode obter atualizações contínuas e ter vários snapshots para marcar várias versões. Você pode usar cada snapshot imediatamente como um clone instantâneo, um repositório editável dedicado ou compartilhado disponível para desenvolvedores, QA ou processos de compilação. Um clone no contexto de uma versão de software específica é um espaço de trabalho.



== Automação com Workload Factory Codebox

A fábrica de carga de trabalho introduz a automação incorporada com o _Codebox_. O Codebox oferece os seguintes benefícios de automação:

* *Geração de snippets de código*: Snippets de infraestrutura como código (IAC) são gerados durante a criação de recursos, permitindo uma integração perfeita com fluxos de trabalho de orquestração existentes.
* *Copiloto de infraestrutura como código*: o Codebox é um copiloto de infraestrutura como código (IaC) que ajuda desenvolvedores e DevOps a gerar código para executar qualquer operação suportada pelo Workload Factory.
* *Visualizador de código e catálogo de automação*: O Codebox fornece um visualizador de código para análise rápida da automação e um catálogo de automação para rápida reutilização futura.




== Custo

Não há custo para usar o recurso Builders do Workload Factory.



== Licenciamento

Não são necessárias licenças especiais da NetApp para usar os recursos do Builders do Workload Factory.



== Regiões

Os construtores têm suporte em todas as regiões comerciais onde o FSX for ONTAP é compatível. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Exibir regiões da Amazon compatíveis."^]

As seguintes regiões da AWS não são suportadas:

* Regiões da China
* Regiões GovCloud (EUA)
* Nuvem secreta
* Top nuvem secreta




== Obter ajuda

O Amazon FSx for NetApp ONTAP é uma solução própria da AWS. Para obter suporte, use a Central de Suporte no seu Console de Gerenciamento da AWS para abrir um chamado. Selecione "FSx para ONTAP" e a categoria, depois forneça as informações necessárias.

Para perguntas gerais sobre o Workload Factory ou aplicativos e serviços do Workload Factory, consultelink:get-help-builders.html["Obtenha ajuda para construtores do Workload Factory"] .
