---
settings:
  name: Builders workloads
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Construtores de cargas de trabalho docs
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
    - title: Limitações conhecidas
      url: "/known-limitations.html"
  - title: Comece agora
    entries:
    - title: Saiba mais sobre a fábrica de cargas de trabalho da BlueXP  para construtores
      url: "/learn-builders.html"
    - title: Início rápido
      url: "/quick-start-builders.html"
    - title: Requisitos
      url: "/requirements-builders.html"
    - title: Integre construtores com Perforce
      url: "/integrate-perforce.html"
  - title: Use cargas de trabalho do Builders
    entries:
    - title: Gerenciar projetos
      url: "/manage-projects.html"
    - title: Criar um espaço de trabalho
      url: "/create-workspaces.html"
    - title: Automatize com Codebox
      url: "/automate-codebox.html"
  - title: Conhecimento e apoio
    entries:
    - title: Registre-se para obter suporte
      url: "/support-registration.html"
    - title: Obtenha ajuda
      url: "/get-help-builders.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
