---
sidebar: sidebar 
permalink: requirements-builders.html 
keywords: Builders, FSx, project, projects 
summary: Certifique-se de que a fábrica de carga de trabalho e a AWS estejam configuradas corretamente antes de começar a usar a fábrica de carga de trabalho do BlueXP  para construtores. Isso inclui ter suas credenciais de login na AWS, um sistema de arquivos FSX for ONTAP implantado e muito mais. 
---
= Requisitos dos construtores
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Certifique-se de que a fábrica de carga de trabalho e a AWS estejam configuradas corretamente antes de começar a usar a fábrica de carga de trabalho do BlueXP  para construtores. Isso inclui ter suas credenciais de login na AWS, um sistema de arquivos FSX for ONTAP implantado e muito mais.

Login e conta de fábrica da carga de trabalho:: Você precisará https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["configure uma conta com a fábrica de carga de trabalho"^] fazer login usando um dos https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
Credenciais e permissões da AWS:: Você precisa adicionar credenciais da AWS ao Workload Factory com permissões de leitura/gravação, o que significa que você usará o Workload Factory no modo _leitura/gravação_ para Builders.


As permissões dos modos _básico_ e _somente leitura_ não são suportadas no momento. https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Saiba como adicionar credenciais da AWS à fábrica de cargas de trabalho"^]

FSX para sistema de arquivos ONTAP:: Você precisa de um mínimo de um sistema de arquivos FSX for ONTAP:
+
--
* O sistema de arquivos será usado pela Builders para armazenar os projetos e espaços de trabalho que você criar.
+
Este sistema de arquivos FSX for ONTAP deve usar o FlexVol volumes. Os volumes FlexGroup não são compatíveis.

* Você precisará conhecer a região, a VPC e a sub-rede da AWS onde reside o sistema de arquivos do AWS FSX for ONTAP.
* Você precisará de pelo menos um volume no sistema de arquivos com a seguinte configuração:
+
** O volume deve ser configurado como um compartilhamento NFS.
** O sistema de arquivos deve ser configurado com um link. https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Saiba mais sobre links"^].


* Você precisará considerar os pares de chave/valor de tag que deseja aplicar aos recursos da AWS que fazem parte dessa implantação (opcional).
+
https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Saiba como implantar e gerenciar os sistemas de arquivos do FSX for ONTAP"^]



--

